
services:
  # Web Server
  web_server:
    container_name: web_server
    depends_on:
      - sql_server
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - ../src/assessment:/var/www/html
    ports:
      - 80:80
      - 433:433

  # Database
  sql_server:
    container_name: sql_server
    image: mariadb:latest
    volumes:
      - ../.database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: db_user
      MARIADB_DATABASE: assessment